FROM s390x/debian:stable-slim

# Setup pre-reqs
RUN apt update && apt -y upgrade
RUN apt -y install wget unzip curl jq

# Download vault:
RUN mkdir -p /vault/data
WORKDIR /vault
RUN wget -q `curl -X GET -s -G --data-urlencode "license_class=enterprise" --data-urlencode "limit=20" https://api.releases.hashicorp.com/v1/releases/vault | jq -r '[.[] | select(.version|test("ent$"))|.version] | sort | last as $url | "https://releases.hashicorp.com/vault/\($url)/vault_\($url)_linux_s390x.zip"'`
RUN unzip `curl -X GET -s -G --data-urlencode "license_class=enterprise" --data-urlencode "limit=20" https://api.releases.hashicorp.com/v1/releases/vault | jq -r '[.[] | select(.version|test("ent$"))|.version] | sort | last as $url | "vault_\($url)_linux_s390x.zip"'`
COPY vault_script.sh vault_script.sh
RUN chmod +x vault_script.sh

EXPOSE 8200

CMD ["/vault/vault_script.sh"]
